"""create parking_spots table

Revision ID: 40f0490e6ffc
Revises: 0f6b9dcf5b9a
Create Date: 2026-05-20 09:18:15.902455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f0490e6ffc'
down_revision: Union[str, Sequence[str], None] = '0f6b9dcf5b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['row_id'], ['parking_rows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row_id', 'code', name='uq_parking_spots_row_code')
    )
    op.create_index(op.f('ix_parking_spots_row_id'), 'parking_spots', ['row_id'], unique=False)
    op.create_index(op.f('ix_parking_spots_status'), 'parking_spots', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parking_spots_status'), table_name='parking_spots')
    op.drop_index(op.f('ix_parking_spots_row_id'), table_name='parking_spots')
    op.drop_table('parking_spots')
    # ### end Alembic commands ###
