"""create parking_spots table

Revision ID: 40f0490e6ffc
Revises: 0f6b9dcf5b9a
Create Date: 2026-05-20 09:18:15.902455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f0490e6ffc'
down_revision: Union[str, Sequence[str], None] = '0f6b9dcf5b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
