"""create guidance_displays table

Revision ID: 8680ade4f45b
Revises: 33d66d76dca9
Create Date: 2026-05-21 10:33:13.441823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8680ade4f45b'
down_revision: Union[str, Sequence[str], None] = '33d66d76dca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guidance_displays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('arrow_direction', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['parking_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guidance_displays_code'), 'guidance_displays', ['code'], unique=True)
    op.create_index(op.f('ix_guidance_displays_zone_id'), 'guidance_displays', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guidance_displays_zone_id'), table_name='guidance_displays')
    op.drop_index(op.f('ix_guidance_displays_code'), table_name='guidance_displays')
    op.drop_table('guidance_displays')
    # ### end Alembic commands ###
