"""create guidance_cameras table

Revision ID: cd1a959a8635
Revises: 40f0490e6ffc
Create Date: 2026-05-20 09:21:46.760756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1a959a8635'
down_revision: Union[str, Sequence[str], None] = '40f0490e6ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guidance_cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=False),
    sa.Column('spots_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['parking_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guidance_cameras_code'), 'guidance_cameras', ['code'], unique=True)
    op.create_index(op.f('ix_guidance_cameras_zone_id'), 'guidance_cameras', ['zone_id'], unique=False)
    op.create_table('parking_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['row_id'], ['parking_rows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row_id', 'code', name='uq_parking_spots_row_code')
    )
    op.create_index(op.f('ix_parking_spots_row_id'), 'parking_spots', ['row_id'], unique=False)
    op.create_index(op.f('ix_parking_spots_status'), 'parking_spots', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parking_spots_status'), table_name='parking_spots')
    op.drop_index(op.f('ix_parking_spots_row_id'), table_name='parking_spots')
    op.drop_table('parking_spots')
    op.drop_index(op.f('ix_guidance_cameras_zone_id'), table_name='guidance_cameras')
    op.drop_index(op.f('ix_guidance_cameras_code'), table_name='guidance_cameras')
    op.drop_table('guidance_cameras')
    # ### end Alembic commands ###
