"""create spot_occupancy_events table

Revision ID: fdf989e20d29
Revises: cd1a959a8635
Create Date: 2026-05-20 09:24:28.771826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf989e20d29'
down_revision: Union[str, Sequence[str], None] = 'cd1a959a8635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot_occupancy_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['guidance_cameras.id'], ),
    sa.ForeignKeyConstraint(['spot_id'], ['parking_spots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spot_occupancy_events_camera_id'), 'spot_occupancy_events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_spot_occupancy_events_dedup_key'), 'spot_occupancy_events', ['dedup_key'], unique=True)
    op.create_index(op.f('ix_spot_occupancy_events_detected_at'), 'spot_occupancy_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_spot_occupancy_events_spot_id'), 'spot_occupancy_events', ['spot_id'], unique=False)
    op.create_index(op.f('ix_spot_occupancy_events_status'), 'spot_occupancy_events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spot_occupancy_events_status'), table_name='spot_occupancy_events')
    op.drop_index(op.f('ix_spot_occupancy_events_spot_id'), table_name='spot_occupancy_events')
    op.drop_index(op.f('ix_spot_occupancy_events_detected_at'), table_name='spot_occupancy_events')
    op.drop_index(op.f('ix_spot_occupancy_events_dedup_key'), table_name='spot_occupancy_events')
    op.drop_index(op.f('ix_spot_occupancy_events_camera_id'), table_name='spot_occupancy_events')
    op.drop_table('spot_occupancy_events')
    # ### end Alembic commands ###
